spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8090"
  cloud:
    gateway:
     routes:
       - id: identity-service
         uri: lb://IDENTITY-SERVICE
         predicates:
           - Path=/auth/**
       - id: new-identity-service
         uri: lb://IDENTITY-SERVICE
         predicates:
           - Path=/user/**


       - id: demande-service
         uri: lb://DEMANDE-SERVICE
         predicates:
           - Path=/demande/**

       - id: budget-service
         uri: lb://BUDGET-SERVICE
         predicates:
           - Path=/budget/**

